carts/urls.py
from django.urls import path
from .views import  CartAddView, CartChangeView, CartRemoveView

app_name = 'all_carts'

urlpatterns = [

    path('cart_add/', CartAddView.as_view(),name='cart_add'),
    path('cart_change/', CartChangeView.as_view(), name='cart_change'),
    path('cart_remove/', CartRemoveView.as_view(),name='cart_remove'),                  

 ]

orders/urls.py
from django.urls import path
from .views import OrderCreateView, user_orders_view

app_name = 'all_orders'

urlpatterns = [
    path('create_order/', OrderCreateView.as_view(), name='create_order'),
    path('user_orders/', user_orders_view,name='user_orders'),
]

product_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # главный сайт с настройками(если product_store.settings не будут работаь)
from django.conf.urls.static import static
from product_store.settings import DEBUG
from products.views import MainPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(),name='main_page'),
    path('products/', include('products.urls', namespace='all_products')),
    path('additional/', include('additional_info.urls', namespace='additional')),
    path('store_users/', include('store_users.urls', namespace='all_users')),
    path('carts/', include('carts.urls', namespace='all_carts')),
    path('orders/', include('orders.urls', namespace='all_orders'))
    ] 


if DEBUG: # будет работать только в режиме разработке, не в продакшене
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))] 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # путь до папки с медиа

products/urls.py
from django.urls import path
from .views import CategoryListView, CurrentProductView,ShowCatalog,Salesproductsview, MainPageView
from django.views.decorators.cache import cache_page # для кэширования наиболее посещаемых страниц

app_name ='all_products'

urlpatterns = [
    # path('', cache_page(60*5)(MainPageView.as_view()), name='main_page'),
    path('catalog/', cache_page(60*5)(ShowCatalog.as_view()), name='products_catalog'),
    path('category/<slug:slug>/',  cache_page(30)(CategoryListView.as_view()), name='subcategories'),
    path('products/<slug:slug>/',  cache_page(30)(CurrentProductView.as_view()), name='current_product'),
    path('sales/',Salesproductsview.as_view(), name='discount'),
    path('search/', CategoryListView.as_view(), name='search')# путь для поисковой системы
    ]

carts/models.py
from django.db import models
# мпорт моделей
from products.models import Product
from store_users.models import StoreUser


# Create your models here.
class CartQuerySet(models.QuerySet):
    '''Вспомогательынй класс для класса Cart, расширяющий функционал базвого менеджжера, вычисляет общую цену товаров и их количество,
    этот класс будет срабатывать, когда мы будем обращаться к QuerySet у класса Cart(Cart.objects.all() например)'''
     
    def general_sum(self):
        '''Возвращает итоговую сумму всех товаров во всех корзинах текущего пользователя'''
        return sum(cart.product_price_in_cart() for cart in self)

    def general_quantity(self):
        '''Возвращает общее количество товаров из всех корзин'''
        if self:
             return sum(cart.quantity for cart in self)
        return 0

class UserCart(models.Model):
    '''модель корзины товаров, отображает товар, цену, количество
    так же есть метолы для расчета общей стоимости, для увеличения 
    и уменьшения количества товара.Логика корзины:для каждого товара создается отдельная корзина, 1 продукт - 1 корзина'''
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, verbose_name='Продукт')
    user = models.ForeignKey(to=StoreUser, on_delete=models.CASCADE,verbose_name='Пользователь',null=True,blank=True)#если юзера нет, по умолчанию ноль(незареганнный юзер)
    quantity = models.PositiveIntegerField(verbose_name='Количество')#количество товара в корзине, инфа для пользователя
    created_timestamp = models.DateTimeField(auto_now_add=True,verbose_name='Дата добавления')
    session_key = models.CharField(max_length=32,null=True,blank=True)# уникальный ключ сессии для каждого неавторизованного бзера,
    objects = CartQuerySet.as_manager() # для связи в вспомогательным классом CartQuerySet

    def __str__(self):
        if self.user:
            return f"Корзина пользователя {self.user.username} с товаром {self.product.name} в количестве {self.quantity}"
        return f"Корзина анонимного пользователя с товаром {self.product.name} в количестве {self.quantity}"
    
    class Meta:
        db_table = 'Cart'# имя таблицы в субд(postgre)
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def product_price_in_cart(self):
        '''Возвращает сумму товара в корзине, в зависимости от количества и скидки'''
        return float(self.product.calculate_sell_price()) * float(self.quantity) # все через float суммировать иначе конфликт decimal и float

carts/views.py
from django.shortcuts import  get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
# импорт классов представлений
from django.views import View
#импорт моделей
from carts.models import UserCart
from products.models import Product
# импорт кастомных миксинов
from common.carts.mixin_views import CartMixin
# вспомогательный инструменты и утилиты
from .utils import get_user_carts
from django.contrib import  messages
import logging
from logger.project_logger import configure_logging
# Create your views here.

logger = logging.getLogger(__name__)
configure_logging(level='INFO')

class CartAddView(CartMixin,View):
    '''Класс для добавления товара в корзину + увеличения его количества в корзине.Прикручен ajax с страницы, что бы она не обнавлялась при каждом изменении'''

    def post(self, request):
            
        try:
            product_id = request.POST.get('product-id') or request.POST.get('product_id')
            if not product_id:# если такого id нет в бд
                return JsonResponse({'status': 'error', 'message': 'Не указан ID товара'}, status=400)
            product = get_object_or_404(Product, id=product_id) # находим товар по id
            current_cart = self.get_cart(request, product=product)

            if current_cart:
                current_cart.quantity +=1
            else:
                if request.user.is_authenticated:
                    UserCart.objects.create(user=request.user,product=product, quantity=1)
                else: 
                    UserCart.objects.create(session_key=request.session.session_key,product=product,quantity=1)
            response_data = {
                'status': 'success',
                'message': f'Товар {product.name} добавлен в корзину',
                'cart_items_html': self.render_cart(request),
            }
            return JsonResponse(response_data)
        except Exception as e:
            logger.error(f"Ошибка добавления в корзину: {str(e)} {product_id}")
            return JsonResponse({
                'status': 'error',
                'message': str(e)
            }, status=400)


class CartChangeView(CartMixin,View):
    '''Контроллер для измения количества товара в корзине при нажатии на кнопки'''

    def post(self,request):
        try:
            cart_id = request.POST.get('cart_id')
            change_cart_quantity = request.POST.get('quantity') # количество в коризну для изменения
            current_cart = self.get_cart(request,cart_id=cart_id)

            current_cart.quantity = change_cart_quantity # текущее количество товаров после изменения
            current_cart.save()


            response_data = { 'message':f"Количество товара {current_cart.product.name} изменено",
                        'cart_items_html' : self.render_cart(request),
                        'quantity' : current_cart.quantity}
            logger.info(f"Количество товара {current_cart.product.name} изменено")
            return JsonResponse(response_data)
        except Exception as err:
            return JsonResponse({
                'status': 'error',
                'message': str(err)
            }, status=400)

class CartRemoveView(CartMixin,View):
    '''контроллер для удаления товаров из корзины'''

    def post(self, request):
        try:
            cart_id = request.POST.get('cart_id')
            current_cart = self.get_cart(request,cart_id=cart_id) # находим корзину которую хотят удлаиь по id
            
            quantity = current_cart.quantity

            current_cart.delete()


            response_data = {'message' : f"Товар {current_cart.product.name} успешно удален из корзины",
                        'cart_items_html' : self.render_cart(request),
                        'quantity_deleted' : quantity}
            
            return JsonResponse(response_data)
        except Exception as err:
            return JsonResponse({
                'status': 'error',
                'message': str(err)
            }, status=400)
        
# контроллеры на основе функиий с прикруткой ajax ручным алгоритмом добавки и т.д (на случай если контроллеры на основе классов перестанут работать)

# def cart_add(request):
#     '''метод для добавления товара в корзину + увеличения его количества в корзине'''
#     try:
#         # 1. Получаем product-id 
#         product_id = request.POST.get('product-id') or request.POST.get('product_id')
#         if not product_id:# если такого id нет в бд
#             return JsonResponse({'status': 'error', 'message': 'Не указан ID товара'}, status=400)
#         # 2. Находим товар
#         product = get_object_or_404(Product, id=product_id)
#         if request.user.is_authenticated:
#             # 3. Ищем существующую корзину (используем get_or_create для атомарности)
#             cart_item, created = UserCart.objects.get_or_create(
#                 user=request.user,
#                 product=product,
#                 defaults={'quantity': 1} # если товаоа не было такого, созлаем его в количестве 1 шт
#             )
#         else:# если юзер не авторизован, то определяем корзину по ключу сессии
#             cart_item, created = UserCart.objects.get_or_create(
#                 session_key=request.session.session_key,
#                 product=product,
#                 defaults={'quantity': 1}
#             )# если товаоа не было такого, созлаем его в количестве 1 шт
#         if not created:# если такой товар уже был
#             cart_item.quantity += 1
#             cart_item.save()
#         # 5. Формируем ответ
#         cart_items_html = render_to_string(
#             'carts/includes/included_cart.html', 
#             {'carts': get_user_carts(request)}, 
#             request=request
#         )
        
#         return JsonResponse({
#             'status': 'success',
#             'message': f'Товар {product.name} добавлен в корзину',
#             'cart_items_html': cart_items_html,
#             'new_quantity': cart_item.quantity,
#             'created': created
#         })
#     except Exception as e:
#         logger.error(f"Ошибка добавления в корзину: {str(e)} {product_id}")
#         return JsonResponse({
#             'status': 'error',
#             'message': str(e)
#         }, status=400)


    # вариант без ajax
    # plus_product = Product.objects.get(slug=product_slug)# есть ли такой товар вообще в базе
    # current_cart = UserCart.objects.filter(user=request.user,product=plus_product)
    # if current_cart.exists():# если такой товар уже был, его количество нужно увеличить на один
    #     user_cart = current_cart.first()
    #     user_cart.quantity +=1
    #     user_cart.save()
    #     messages.success(request,f"Теперь у вас {user_cart.quantity} шт. {plus_product.name}")
    # else:# иначе добавим этот товар в корзину в количестве 1 шт.
    #     messages.success(request,f"{plus_product.name} успешно добавлен в корзину")
    #     UserCart.objects.create(user=request.user,product=plus_product,quantity=1)
    # return HttpResponseRedirect(request.META['HTTP_REFERER']) # поосле изменения количества товара возвращаем юзера на туже страницу где он и был

# def cart_change(request):
#     '''Контроллер для измения количества товара в корзине при нажатии на кнопки'''
#     cart_id = request.POST.get('cart_id')
#     change_cart_quantity = request.POST.get('quantity') # количество в коризну для изменения
#     current_cart = UserCart.objects.get(id=cart_id)# текущая корзину юзеа по данному id
#     logger.info(f"инфа из post запроса на изменение товаров в корзине {request.POST}")

#     current_cart.quantity = change_cart_quantity# изменяем текущее количество товаров данной корзины
#     current_cart.save()

#     all_users_cart =get_user_carts(request) # берем все корзины юзера уже полсе изменения для перерисовки на странице

#     cart_items_html = render_to_string('carts/includes/included_cart.html', {'cart' : all_users_cart}, request=request)
#     response_data = { 'message':f"Количество товара {current_cart.product.name} изменено",
#                      'cart_items_html' : cart_items_html,
#                      'quantity' : current_cart.quantity}    
    
#     return JsonResponse(response_data)

    # # алгоритм уменьшения единиц товара без ajax
    # if minus_cart.exists():
    #     minus_product = minus_cart.first()
    #     if minus_product.quantity > 1:# уменьшаем количество товаров
    #         minus_product.quantity -= 1
    #         minus_product.save()
    #     else:
    #         minus_product.delete()# удаляем данный товар из корзиный
            
    # return HttpResponseRedirect(request.META['HTTP_REFERER']) 

# def cart_remove(request):

#     logger.warning(f"Вот инфа для  удаления {request.POST}")
#     cart_id = request.POST.get('cart_id') # находим текущую корзину по id
#     if not cart_id:
#         logger.warning(f"Ошибка с словарем POST запроса {request.POST}")
#         raise ValueError('В post запросе другой ключ словаря к id')
#     try:
#         if request.user.is_authenticated:
#             current_cart = UserCart.objects.get(id=cart_id)
#         else:
#             current_cart = UserCart.objects.get(id=cart_id,session_key=request.session.session_key) # что бы найти корзину невториз. юзера
#     except Exception as error:
#         logger.error(f"В БД нет корзины с id {cart_id}, {error}")
#     else:    
#         current_cart.delete()
#         logger.warning(f"продукт {current_cart.product.name} успешно удален")

#     if current_cart.quantity > 0: # что бы грамотно работала отрисовка товаров в корзине полсе удаления, иначе булет отрицательный показатель корзины
#         quantity = current_cart.quantity

#     user_cart = get_user_carts(request) # возвращаем обновленную корзину с удаленнымми товарами
#     cart_items_html = render_to_string('carts/includes/included_cart.html', {'cart':user_cart}, request=request)

carts/templates/carts/includes/cart_button.html
{%load static%}
{%load carts_tag%}


{%user_carts request as carts%}

<div>
    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
        aria-expanded="false">
        <img class="mx-1" src="{%static 'deps/icons/basket2-fill.svg'%}" alt="Catalog Icon" width="24"
            height="24">
        <span id="goods-in-cart-count">{{carts.general_quantity}} </span>  
    </button>
</div>
<!-- Разметка модального окна корзины -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {%include 'carts/includes/included_cart.html'%}
                    <!-- Закончилась разметка корзины -->
                </div>

            </div>
        </div>
    </div>
</div>

carts/templates/carts/includes/included_cart.html
{%load static%}
{%load carts_tag%}
{%user_carts request as carts%}
<div class="card mb-3 text-bg-light shadow-lg">
    {%for cart in carts%}
            <div class="card-header">
                <h5 class="card-title"><font color='blue'>{{cart.product.name}}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="row text-center">
                        <div class="col p-0">
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-dark btn-sm decrement"
                                        data-cart-id="{{cart.id}}" data-cart-change-url="{%url 'all_carts:cart_change'%}">
                                        {%csrf_token%}
                                        -
                                    </button>
                                </span>
                                <input type="text" class="form-control number" value="{{cart.quantity}}"
                                    readonly>
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-dark btn-sm increment"
                                        data-cart-id="{{cart.id}}" data-cart-change-url="{%url 'all_carts:cart_change'%}">
                                        {%csrf_token%}
                                        +
                                    </button>
                                </span>
                            </div>
                        </div>
                        <div class="col p-0">
                            <p>x {{cart.product.calculate_sell_price}} руб. = </p>
                        </div>
                        <div class="col p-0"><strong>{{cart.product_price_in_cart}}руб.</strong></div>
                        <div class="col p-0">
                            <a href="{% url 'all_carts:cart_remove'%}" class="remove-from-cart" data-cart-id="{{cart.id}}">
                                {%csrf_token%}
                                Удалить
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
    {%endfor%}
</div>
{%if carts.first.quantity >= 1%}
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Итого <strong>{{carts.general_quantity}}</strong> товар(а) на сумму</p>
        <h4 class="float-left"><strong>{{carts.general_sum}} руб.</strong></h4>
    </div>
</div>
{%else%}
    <h3>Нет товаров в корзине</h3>
    <h4><a href="{%url 'all_products:products_catalog'%}">К покупкам</a></h4>
{%endif%}
{%if carts and title != 'Оформление заказа' and not order%}
<a class="btn btn-dark" href="{%url 'all_orders:create_order'%}">
    Оформить заказ
</a>
{%endif%}