carts/urls.py
from django.urls import path
from .views import  CartAddView, CartChangeView, CartRemoveView

app_name = 'all_carts'

urlpatterns = [

    path('cart_add/', CartAddView.as_view(),name='cart_add'),
    path('cart_change/', CartChangeView.as_view(), name='cart_change'),
    path('cart_remove/', CartRemoveView.as_view(),name='cart_remove'),                  

 ]

product_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # главный сайт с настройками(если product_store.settings не будут работаь)
from django.conf.urls.static import static
from product_store.settings import DEBUG
from products.views import MainPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(),name='main_page'),
    path('products/', include('products.urls', namespace='all_products')),
    path('additional/', include('additional_info.urls', namespace='additional')),
    path('store_users/', include('store_users.urls', namespace='all_users')),
    path('carts/', include('carts.urls', namespace='all_carts')),
    path('orders/', include('orders.urls', namespace='all_orders'))
    ] 


if DEBUG: # будет работать только в режиме разработке, не в продакшене
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))] 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # путь до папки с медиа

products/urls.py
from django.urls import path
from .views import CategoryListView, CurrentProductView,ShowCatalog,Salesproductsview, MainPageView
from django.views.decorators.cache import cache_page # для кэширования наиболее посещаемых страниц

app_name ='all_products'

urlpatterns = [
    # path('', cache_page(60*5)(MainPageView.as_view()), name='main_page'),
    path('catalog/', cache_page(60*5)(ShowCatalog.as_view()), name='products_catalog'),
    path('category/<slug:slug>/',  cache_page(30)(CategoryListView.as_view()), name='subcategories'),
    path('products/<slug:slug>/',  cache_page(30)(CurrentProductView.as_view()), name='current_product'),
    path('sales/',Salesproductsview.as_view(), name='discount'),
    path('search/', CategoryListView.as_view(), name='search')# путь для поисковой системы
    ]

store_users/urls.py
from django.urls import path
from .views import UserRegistrationView, UserLoginView, UserProfileView, logout, UserCartView, UserVerifyView, UserChangePassword
from django.contrib.auth.decorators import login_required

app_name = 'all_users'

urlpatterns = [

    path('register/', UserRegistrationView.as_view(),name='current_registration'),
    path('login/', UserLoginView.as_view(), name='current_login'),
    path('profile/', login_required(UserProfileView.as_view()),name='current_profile'),
    path('logout/', logout,name='logout'),
    path('user_cart/',UserCartView.as_view(), name='user_cart'),
    path('change_password/' , UserChangePassword.as_view(), name='change_password'),
    path('verify_data/', UserVerifyView.as_view(), name='verify_user')                  

]

store_users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class StoreUser(AbstractUser):
    '''Модель пользователей магазина с личными данными, фото, также применяется для форм автор и аутентификации
    Мы расширяем базовую таблицу из auth'''
    image = models.ImageField(upload_to='user_images',null=True, blank=True, verbose_name='Аватарка')
    email = models.EmailField(verbose_name='адрес электронной почты', unique=True)
    phone_number = models.CharField(max_length=18, blank=True, null= True)
    code_word = models.CharField(max_length=15, verbose_name='кодовое слово', null=True,blank=True)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ['username']

    def __str__(self):

            if self.is_superuser:
                return f"Пользователь {self.username} с правами админа"
            elif self.is_staff:
                 return f"Пользователь {self.username} с правами работника"
            return f"Пользователь {self.username}"
    
    def get_full_name(self):
         return super().get_full_name()

orders/forms.py
from django import forms
from .models import UserOrders

class OrderForm(forms.ModelForm):
    '''форма для зшаблона страницы с заказами юзера с завязкой на бэкенд'''

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : "form-control",
        'placeholder' : 'Введите имя'}))
    second_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : "form-control",
        'placeholder' : 'Введите фамилию'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'placeholder' : '+7 (XXX) XXX-XX-XX'
                                        }),initial='+7')
    email  = forms.EmailField(widget=forms.EmailInput(attrs={
        'class' : 'form-control',
        'placeholder' : "you@example.com"}))
    requires_delivery = forms.ChoiceField(widget=forms.RadioSelect(),choices=
                                         [('0', False),
                                          ('1', True)], initial='0',help_text='требует доставки')
    delivery_address = forms.CharField(required=False,widget=forms.Textarea(attrs={
            'class' : 'form-control',
            'id' : 'delivery-address',
            'rows' : 2,
            'placeholder' : 'Пример адреса: Россия, Москва, ул. Мира, дом 6'
                                        }))
    payment_type = forms.ChoiceField(widget=forms.RadioSelect(),choices=
                                         [('0', 'Оплата по карте'),
                                          ('1', 'Наличка')],
                                          initial='0')
    
    class Meta:
        model= UserOrders
        fields = ['first_name', 'second_name','email','requires_delivery', 'delivery_address','payment_type']

class OrderFormAlternative(forms.Form):
    '''Доп форма, не привязанная к ModelForm(без MEta класса), т.к может пригодиться кастомная валидаци. Завязка на фронтенд'''

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField()
    delivery_address = forms.CharField(required=False) # необязательно
    payment_type = forms.ChoiceField()
    email = forms.CharField()
    address = forms.CharField()

    class Meta:
        model= UserOrders
        fields = {'first_name', 'last_name','phone_number', 'requires_delivery', 'delivery_address','payment_type','email','address'}



    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : "form-control",
        'placeholder' : 'Введите имя'}))
    second_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : "form-control",
        'placeholder' : 'Введите фамилию'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'placeholder' : 'Введите номер телефона'
                                        }))
    email  = forms.EmailField(widget=forms.EmailInput(attrs={
        'class' : 'form-control',
        'placeholder' : "you@example.com"}))
    adress = forms.CharField(widget=forms.TextInput(attrs={
        'class' : "form-control",
        'placeholder' : 'Пример адреса: Россия, Москва, ул. Мира, дом 6'}))
    requires_delivery = forms.ChoiceField(widget=forms.RadioSelect(),choices=
                                         [('0', False),
                                          ('1', True)])
    delivery_address = forms.CharField(widget=forms.Textarea(attrs={
            'class' : 'form-control',
            'id' : 'delivery-address',
            'rows' : 2,
            'placeholder' : 'Введите адрес доставки'
                                        }))
    payment_type = forms.ChoiceField(widget=forms.RadioSelect(),choices=
                                         [('0', False),
                                          ('1', True)],
                                          initial='card')
    

store_users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from .models import StoreUser



class UserLoginForm(AuthenticationForm):
    '''форма для аутентификации юзера, валидации вводимых данных'''
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = StoreUser # модель, в которую будут поступать валидные данные из формы авторизации
        fields = ['username','password']
        labels = {'username':'ВВедите имя пользователя','password':'Введите пароль'}


class UserRegistrationForm(UserCreationForm):
    '''Форма для регистрации юзера + валидация вводимых данных'''
    #атрибуты при слиянии бэка с фронтом
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Подтвердите пароль'}))
    code_word = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Кодовое слово на случай утраты пароля'}))
    
    class Meta:
        model = StoreUser
        fields = ['username','first_name','last_name','email','password1','password2', 'code_word']

    def save(self, commit = True):
        new_user = super().save(commit=commit) 
        # new_user = super(UserCreationForm,self).save(commit=True)# сохранение нового юзера в бд
        return new_user
    
class UserProfileForm(UserChangeForm):
    '''Форма для отоббражения полей профиля пользователя с возможностью 
    CRUD операций + аватарку поставить'''
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите имя пользователя'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите фамилию'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите адрес эл. почты'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class':'form-control mt-3',
        'placeholder' : 'Выберите изображение'}),required=False)
    class Meta:
        model = StoreUser
        fields = ['username','first_name','last_name','email','image']


class VerifyCodeWordForm(forms.Form):
    '''форма для верификации кодового слова при смене пароля'''
    username = forms.CharField(label='имя пользователя')
    code_word = forms.CharField(label='кодовое слово')
    email = forms.CharField(label='почта пользователя')

    def clean(self):
        cleaned_data =super().clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')
        code_word =  cleaned_data.get('code_word')
        try:
            current_user = StoreUser.objects.get(username=username, email=email)
        except StoreUser.DoesNotExist as err:
            raise forms.ValidationError(f'Пользователь с таким именем или почтой не найден')
        if current_user.code_word != code_word:
                raise forms.ValidationError('Неверное кодовое слово')
        return cleaned_data
    
class NewPasswordForm(forms.Form):
    '''форма для ввода нового пароля верифицированного пользователя'''
    password1 = forms.CharField(label='новый пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='подтверждение пароля', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('password1') != cleaned_data.get('password2'):
            raise forms.ValidationError('пароли не совпадают')
        return cleaned_data

store_users/templates/store_users/change_password.html
{%extends 'products/base.html'%}
{%load static%}

{%block title%}
{{title}}
{%endblock%}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-7 col-lg-5 bg-white p-5 rounded shadow-sm">

            {% if step == 1 %}
                <h2 class="mb-4 text-center">Пройдите верификацию</h2>
            {% elif step == 2 %}
                <h2 class="mb-4 text-center">Введите новый пароль</h2>
            {% endif %}

            <form method="post" action="{{form_action}}">
                {% csrf_token %}

                {%for atr in form%}
                
                    <div class="col-md-6 mb-3">
                        <label for="{{atr.id_for_label}}" class="form-label">{{atr.label}}</label>
                        {{atr}}
                        {%if atr.errors%}
                        <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">{{atr.errors}}</div>

                        {%endif%}
                    </div>
                {%endfor%}
                {% if step == 1 %}
                <button type="submit" class="btn btn-primary w-100 mt-3">Подтвердить данные</button>
                {% elif step == 2 %}
                    <button type="submit" class="btn btn-primary w-100 mt-3">Сменить пароль</button>
                {% endif %}
            </form>

        </div>
    </div>
</div>
{% endblock %}

store_users/templates/store_users/login.html
{% extends "products/base.html"%}
{%load static%}

{%block title%}
{{title}}
{%endblock%}

{%block modal_cart%}
    {%include 'carts/includes/cart_button.html'%}
{%endblock%}

{%block content%}
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                                    <h2 class="text-center mb-4">Авторизация</h2>
                                    <form action="{%url 'all_users:current_login'%}" method='post'>
                                        {% csrf_token %}

                                        <div class="mb-3">
                                            <label for="id_username" class="form-label">Имя пользователя</label>
                                            <input type="text" class="form-control" value="{%if form.username.value%}{{form.username.value}}{%endif%}" name="username" id="id_username" placeholder="Введите ваше имя пользователя" required>
                                        </div>
                                        <div class="mb-3">
                                            <label for="id_password" class="form-label">Пароль</label>
                                            <input type="password" class="form-control" name="password" id="id_password" placeholder="Введите ваш пароль" required>
                                        </div>
                                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                                        <div class="mt-3">
                                            <a href="{%url 'all_users:verify_user'%}">Забыли пароль?</a> | <a href="{%url 'all_users:current_registration'%}">Создать аккаунт</a>
                                        </div>
                                        <hr>
                                        <div class="text-center">
                                            <p>Или авторизуйтесь через:</p>
                                            <a href="#" class="btn btn-dark">
                                                <img class="mx-1" src="{%static 'deps/icons/google.svg'%}" alt="Catalog Icon" width="16" height="16">
                                                Google
                                            </a>
                                            <a href="#" class="btn btn-dark">
                                                <img class="mx-1" src="{%static 'deps/icons/facebook.svg'%}" alt="Catalog Icon" width="16" height="16">
                                                Facebook
                                            </a>
                                            <a href="#" class="btn btn-dark">
                                                <img class="mx-1" src="{% static 'deps/icons/github.svg'%}" alt="Catalog Icon" width="16" height="16">
                                                GitHub
                                            </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{%endblock%}

store_users/templates/store_users/profile.html
{% extends "products/base.html"%}
{%load static%}
{%load cache%}

{%block title%}
{{title}}
{%endblock%}
{%block content%}
<!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row">
                                <!-- Профиль с данными пользователя -->
                                <div class="col-md-5">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Профиль пользователя {{user.username}}</h3>
                                        <form action="{%url 'all_users:current_profile'%}" method='post' enctype="multipart/form-data">
                                            <div class="col-md-12 mb-3 text-center">
                                                <label for="{{form.image.id_for_label}}" class="form-label">Ваш профиль</label>
                                                <img src="{%if user.image%}{{user.image.url}}{%else%}{%static 'deps/images/baseavatar.jpg'%}{%endif%}"
                                                    alt="Аватар пользователя" class="img-fluid rounded-circle";>
                                            </div>
                                            {%if form.image.errors%}
                                                        <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">{{form.image.errors}}</div>
                                            {%endif%}
                                            {%csrf_token%}
                                            <div class="row">
                                                {%for attr in form%}
                                                    {%if attr.id_for_label != id_password%}
                                                        <div class="col-md-12 mb-3">
                                                            <label for="{{attr.id_for_label}}" class="form-label">{{attr.label}}</label>
                                                            {{attr}}
                                                        </div>
                                                        {%if attr.errors%}
                                                        <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">{{attr.errors}}</div>
                                                        {%endif%}
                                                    {%endif%}
                                                {%endfor%}
                                            </div>
                                            <button type="submit" class="btn btn-dark">Сохранить</button>
                                        </form>
                                    </div>
                                </div> 
                                <!-- Корзина -->
                                        <div class="col-md-7">
                                            <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                                <h3 class="text-center mb-4">Корзина</h3>
                                                <div class="container" id="cart-items-container">
                                                    <!-- Разметка корзины -->
                                                    {%include 'carts/includes/included_cart.html'%}
                                                    <!-- Закончилась разметка корзины -->
                                                </div>
                                            </div>
                                        </div>
                                <!-- Оформленные заказы -->
                                {% comment %} {%cache 60 user_orders user.id%} {% endcomment %}
                                 <div class="col-md-12">
                                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                    <h3 class="text-center mb-4">Мои заказы</h3>
                                    <!-- Разметка заказов -->
                                    <div class="container">
                                        <div class="accordion" id="accordionExample">
                                            {%if orders.exists%}
                                                {% for order in orders %}
                                                        {%if order.created_timestamp%}
                                                            <div class="accordion-item">
                                                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                                                        Заказ № {{ order.id }} - {{ order.created_timestamp }} | Статус: <strong class="mx-2">{{order.status}}</strong>
                                                                    </button>
                                                                </h2>
                                                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                                                    <div class="accordion-body">
                                                                        <table class="table table-dark table-hover">
                                                                            <thead>
                                                                                <tr>
                                                                                    <th>Товар</th>
                                                                                    <th>Количество</th>
                                                                                    <th>Цена</th>
                                                                                    <th>Общая стоимость</th>
                                                                                </tr>
                                                                            </thead>
                                                                            <tbody>
                                                                                {% for item in order.order_items.all %}
                                                                                    {%if item.product_price%}
                                                                                        <tr>
                                                                                            <td><a class="text-white" href="{% url 'all_products:current_product' item.product.slug %}">{{ item.product.name }}</a></td>
                                                                                            <td>{{ item.quantity }}</td>
                                                                                            <td>{{ item.price }}</td>
                                                                                            <td>{{ item.total_price }}</td>
                                                                                        </tr>
                                                                                    {%endif%}
                                                                                {% endfor %}
                                                                            </tbody>
                                                                        </table>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        {%endif%}
                                                {% endfor %}
                                            {%else%}
                                              <h2><font color=blue>В данный момент у вас нет заказов.</h2>
                                            {%endif%}
                                        </div>
                                    </div>
                                    </div>
                                {% comment %} {%endcache%} {% endcomment %}
                                </div>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
{%endblock%}

store_users/templates/store_users/registration.html
{% extends "products/base.html"%}
{%load static%}
{% load widget_tweaks %}

{%block title%}
{{title}}
{%endblock%}

{%block content%}
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">Регистрация</h2>
                    <form action="{%url 'all_users:current_registration'%}" method='post'>
                        {%csrf_token%}
                        <div class="row">
                            {%for atr in form%}
                            
                                <div class="col-md-6 mb-3">
                                    <label for="{{atr.id_for_label}}" class="form-label">{{atr.label}}</label>
                                    {{atr}}
                                    {%if atr.errors%}
                                    <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">{{atr.errors}}</div>

                                    {%endif%}
                                </div>
                            {%endfor%}
                        </div> 

                        <!-- Отвязка бэка от фронта-->
                        {% comment %} <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" name='first_name' value="{%if form.first_name.value%}{{form.first_name.value}}{%endif%}"class="form-control" id="id_first_name"
                                    placeholder="Введите ваше имя" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_second_name" class="form-label">Фамилия*</label>
                                <input type="text" name='last_name' value="{%if form.second_name.value%}{{form.second_name.value}}{%endif%}" class="form-control" id="id_second_name"
                                    placeholder="Введите вашу фамилию" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" name='username' value="{%if form.username.value%}{{form.username.value}}{%endif%}" class="form-control" id="id_username"
                                    placeholder="Введите ваше имя пользователя" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" name='email' value="{%if form.email.value%}{{form.email.value}}{%endif%}"    class="form-control" id="id_email"
                                    placeholder="Введите ваш email" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">Пароль*</label>
                                <input type="password" name='password1' class="form-control" id="id_password1"
                                    placeholder="Введите пароль" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" name='password2' class="form-label">Подтверждение пароля*</label>
                                <input type="password" class="form-control" id="id_password2"
                                    placeholder="Подтвердите пароль" required>
                            </div>
                        </div>  {% endcomment %}
                        <button type="submit"
                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
{%endblock%}